
[tool.black]
line-length = 119
target-version = ['py38']

[tool.mypy]
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
